### ISSUE TITLE
update node versions in Dockerfiles

### ISSUE THREAD

**Issue by coeit** [Zendro-dev/zendro#36]
## Issue

This issue serves as a combined fix for updating the node version in all Dockerfiles in their corresponding repositories. They are:

```
Dockerfile.spa
Dockerfile.graphiql
Dockerfile.graphql-server
```

When running `zendro dockerize -u` an error occurs, that the "http://deb.debian.org/debian stretch-updates/main amd64 Packages" cannot be found. It looks like that library is deprecated, see https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html. The currently used node:16-strech-slim seems to use that library which thows the error upon building the images.

Updating the base node image should fix this.

**Comment by qwerdenkerXD** [comment]
Already satisfied. See #15
